# Generated by Django 3.1.7 on 2021-04-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmainpage',
            name='show_n',
            field=models.IntegerField(default=4),
        ),
    ]
