# Generated by Django 3.1.7 on 2021-04-08 03:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lab_title', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('carousel_field', wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock([('carousel_title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False)), ('images', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True)),
                ('page_field', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(required=False))], blank=True)),
                ('about_us', wagtail.core.fields.RichTextField(blank=True)),
                ('org_title', models.CharField(blank=True, max_length=255, null=True)),
                ('org_address', models.CharField(blank=True, max_length=255, null=True)),
                ('org_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('disclaimer_url', models.URLField(blank=True, null=True)),
                ('group_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('org_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
