# Generated by Django 3.1.7 on 2021-04-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_n_news',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_n_pub',
            field=models.IntegerField(default=10),
        ),
    ]
