# Generated by Django 3.1.7 on 2021-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationspage',
            name='show_front',
            field=models.BooleanField(default=False),
        ),
    ]
