# Generated by Django 3.1.7 on 2021-04-08 15:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20210408_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationspage',
            name='page_field',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(required=False))], blank=True),
        ),
    ]
