# Generated by Django 3.1.7 on 2021-04-08 15:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publicationspage_page_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationspage',
            name='page_field',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.CharBlock(required=False))], blank=True),
        ),
    ]
