# Generated by Django 3.1.7 on 2021-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemainpage',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
