# Generated by Django 3.1.7 on 2021-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_peoplepage_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='category',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('phd-student', 'PhD-Student'), ('student', 'Student'), ('visiting-scholar', 'Visiting-Scholar'), ('alumni', 'Alumni')], default='Student', max_length=25),
        ),
    ]
